wallpaper {
    monitor = DP-3
    path = /home/lesley/Documenten/Wallpaper/lain3.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-5
    path = /home/lesley/Documenten/Wallpaper/lain1.png
    fit_mode = cover
}

splash = false
