wallpaper {
    monitor = DP-3
    path = /home/lesley/Documenten/Wallpaper/2ellen.png
    fit_mode = cover
}

wallpaper {
    monitor = DP-5
    path = /home/lesley/Documenten/Wallpaper/1ellen.png
    fit_mode = cover
}

splash = false
